# Generated by Django 5.2.6 on 2025-12-17 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('key', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pin', models.CharField(default=None, editable=False, max_length=128, null=True)),
                ('pin_attempt', models.JSONField(default=dict, editable=False)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'user'], name='api_devicet_device__145fa7_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'user'), name='uniq_user_device')],
            },
        ),
    ]
