# Generated by Django 5.2.6 on 2025-12-28 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('main', '0014_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='bazaar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='main.bazaar'),
        ),
    ]
