# Generated by Django 5.2.6 on 2025-10-10 11:01

from django.db import migrations

from smartbozor.partition import create_partition_table_sql


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
                          CREATE TABLE rent_thingstatus
                          (
                              id             BIGSERIAL NOT NULL,
                              bazaar_id      BIGINT    NOT NULL,
                              thing_id       BIGINT    NOT NULL,
                              number         INTEGER   NOT NULL,
                              date           DATE      NOT NULL,
                              is_occupied    BOOLEAN   NOT NULL DEFAULT FALSE,
                              is_paid        BOOLEAN   NOT NULL DEFAULT FALSE,
                              payment_method INTEGER   NOT NULL DEFAULT 0,
                              price          INTEGER   NOT NULL DEFAULT 0,
                              occupied_at    TIMESTAMPTZ        DEFAULT NULL,
                              paid_at        TIMESTAMPTZ        DEFAULT NULL,
                              click_status   SMALLINT  NOT NULL DEFAULT 0,
                              payme_status   SMALLINT  NOT NULL DEFAULT 0,
                              CONSTRAINT rent_thingstatus_pkey PRIMARY KEY (id, date)
                          ) PARTITION BY RANGE ("date");
                          """,
                          reverse_sql="DROP TABLE rent_thingstatus"),
        migrations.RunSQL(create_partition_table_sql("rent_thingstatus", 0, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("rent_thingstatus", 1, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("rent_thingstatus", 2, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("rent_thingstatus", 3, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("rent_thingstatus", 4, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("rent_thingstatus", 5, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            "CREATE INDEX rent_thingstatus_bid_thid_num_date ON rent_thingstatus (bazaar_id, thing_id, number, date);",
            reverse_sql="DROP INDEX rent_thingstatus_bid_thid_num_date;",
        ),
    ]
