# Generated by Django 5.2.6 on 2025-10-10 11:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_bazaar_rent_pdf_bazaar_shop_pdf_bazaar_stall_pdf'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Kun')),
                ('is_occupied', models.BooleanField(default=False, verbose_name="Band bo'lgan")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'lov qilingan")),
                ('payment_method', models.IntegerField(default=0, verbose_name="To'lov turi")),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('occupied_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Band qilingan sana')),
                ('paid_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name="To'lov qilingan sana")),
                ('click_status', models.SmallIntegerField(default=0)),
                ('payme_status', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Buyum holati',
                'verbose_name_plural': 'Buyum holatlari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Buyum',
                'verbose_name_plural': 'Buyumlar',
            },
        ),
        migrations.CreateModel(
            name='ThingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Netcha mavjud')),
                ('price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ijara narxi')),
                ('bazaar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.bazaar', verbose_name='Bozor')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rent.thing', verbose_name='Buyum')),
            ],
            options={
                'verbose_name': 'Bozordagi buyum',
                'verbose_name_plural': 'Bozordagi buyumlar',
                'unique_together': {('thing', 'bazaar')},
            },
        ),
    ]
