# Generated by Django 5.2.6 on 2025-10-11 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingdata',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Netcha mavjud'),
        ),
    ]
