# Generated by Django 5.2.6 on 2025-12-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_thingdata_count'),
    ]

    operations = [
        migrations.RunSQL(
            """ALTER TABLE rent_thingstatus RENAME COLUMN click_status TO payment_progress;""",
            reverse_sql="""ALTER TABLE rent_thingstatus RENAME COLUMN payment_progress TO click_status;"""
        ),
        migrations.RunSQL(
            """ALTER TABLE rent_thingstatus DROP COLUMN payme_status;""",
            reverse_sql="""ALTER TABLE rent_thingstatus
                ADD COLUMN payme_status SMALLINT DEFAULT 0;"""
        ),
    ]
