# Generated by Django 5.2.6 on 2025-10-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('can_view_total_revenue', 'Can view total revenue'), ('can_view_total_scan', 'Can view total scan')]},
        ),
    ]
