# Generated by Django 5.2.6 on 2025-09-25 20:27

from django.db import migrations

from smartbozor.partition import create_partition_table_sql


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
                          CREATE TABLE parking_parkingstatus
                          (
                              id             BIGSERIAL             NOT NULL,
                              parking_id     BIGINT                NOT NULL,
                              date           DATE                  NOT NULL,
                              number         CHARACTER VARYING(20) NOT NULL,
                              is_paid        BOOLEAN               NOT NULL DEFAULT FALSE,
                              payment_method INTEGER               NOT NULL DEFAULT 0,
                              price          INTEGER               NOT NULL DEFAULT 0,
                              duration       INTEGER               NOT NULL DEFAULT 0,
                              enter_count    INTEGER               NOT NULL DEFAULT 0,
                              leave_count    INTEGER               NOT NULL DEFAULT 0,
                              enter_at       TIMESTAMPTZ                    DEFAULT NULL,
                              leave_at       TIMESTAMPTZ                    DEFAULT NULL,
                              paid_at        TIMESTAMPTZ                    DEFAULT NULL,
                              enter_image    CHARACTER VARYING(100) NULL DEFAULT NULL,
                              leave_image    CHARACTER VARYING(100) NULL DEFAULT NULL,
                              click_status   SMALLINT              NOT NULL DEFAULT 0,
                              payme_status   SMALLINT              NOT NULL DEFAULT 0,
                              CONSTRAINT parking_parkingstatus_pkey PRIMARY KEY (id, "date")
                          ) PARTITION BY RANGE ("date");
                          """,
                          reverse_sql="DROP TABLE parking_parkingstatus"),
        migrations.RunSQL(create_partition_table_sql("parking_parkingstatus", 0, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("parking_parkingstatus", 1, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("parking_parkingstatus", 2, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("parking_parkingstatus", 3, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("parking_parkingstatus", 4, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("parking_parkingstatus", 5, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            "CREATE INDEX parking_parkingstatus_parking_id_date_idx ON parking_parkingstatus (parking_id, date, number);",
            reverse_sql="DROP INDEX parking_parkingstatus_parking_id_date_idx;",
        ),
    ]
