# Generated by Django 5.2.6 on 2025-10-12 07:50

import apps.parking.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_bazaar_rent_pdf_bazaar_shop_pdf_bazaar_stall_pdf'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('number', models.CharField(max_length=20, verbose_name='Avtoraqam')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('payment_method', models.IntegerField(default=0, verbose_name="To'lov turi")),
                ('price', models.IntegerField(default=0, verbose_name='Narxi')),
                ('duration', models.IntegerField(default=0, verbose_name='Davomiyligi')),
                ('enter_at', models.DateTimeField(verbose_name='Kirgan vaqti')),
                ('leave_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Chiqqan vaqti')),
            ],
            options={
                'verbose_name': 'Avtoturargoh holati',
                'verbose_name_plural': 'Avtoturargoh holatlari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Turargoh nomi/raqami')),
                ('bazaar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.bazaar', verbose_name='Bozor')),
            ],
            options={
                'verbose_name': 'Avtoturargoh',
                'verbose_name_plural': 'Avtoturargohlar',
            },
        ),
        migrations.CreateModel(
            name='ParkingCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(0, 'Kirish'), (1, 'Chiqish')], default=0, verbose_name='Roli')),
                ('mac', models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='MAC')),
                ('token', models.CharField(default=apps.parking.models.generate_token, editable=False, max_length=32, unique=True, verbose_name='Token')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking.parking', verbose_name='Avtoturargoh')),
            ],
            options={
                'verbose_name': 'Kamera',
                'verbose_name_plural': 'Kameralar',
            },
        ),
        migrations.CreateModel(
            name='ParkingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, help_text="Ko'rsatilgan qiymatdan o'tsa narx hisoblanadi. Masalan 3600 qo'yilsa, 1 soatdan oshsa ma'noni anglatadi.", verbose_name='Davomiyligi (sekundda)')),
                ('price', models.IntegerField(help_text="Agar 0 qo'yilsa, tekin ekanligini anglatadi", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking.parking', verbose_name='Avtoturargoh')),
            ],
            options={
                'verbose_name': 'Avtoturargoh narxi',
                'verbose_name_plural': 'Avtoturargoh narxlari',
            },
        ),
        migrations.CreateModel(
            name='ParkingWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100, verbose_name='Regex')),
                ('bazaar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.bazaar', verbose_name='Bozor')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.district', verbose_name='Tuman')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': "Oq ro'yxat",
                'verbose_name_plural': "Oq ro'yxat",
            },
        ),
    ]
