# Generated by Django 5.2.6 on 2025-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='billing_mode',
            field=models.SmallIntegerField(choices=[(0, 'Pulni kirishi bilan hisoblash'), (1, 'Pulni chiqishda hisoblash')], default=1),
        ),
        migrations.AddField(
            model_name='parking',
            name='save_image',
            field=models.BooleanField(default=False, verbose_name='Rasmlarni saqlash'),
        ),
    ]
