# Generated by Django 5.2.6 on 2025-11-05 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parking_billing_mode_parking_save_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingprice',
            name='duration',
            field=models.IntegerField(default=0, help_text="Ko'rsatilgan qiymatdan o'tsa narx hisoblanadi. Masalan 3600 qo'yilsa, 1 soatdan oshsa ma'noni anglatadi.", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Davomiyligi (sekundda)'),
        ),
    ]
