# Generated by Django 5.2.6 on 2025-12-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_parkingprice_duration'),
    ]

    operations = [
        migrations.RunSQL(
            """ALTER TABLE parking_parkingstatus RENAME COLUMN click_status TO payment_progress;""",
            reverse_sql="""ALTER TABLE parking_parkingstatus RENAME COLUMN payment_progress TO click_status;"""
        ),
        migrations.RunSQL(
            """ALTER TABLE parking_parkingstatus DROP COLUMN payme_status;""",
            reverse_sql="""ALTER TABLE parking_parkingstatus
                ADD COLUMN payme_status SMALLINT DEFAULT 0;"""
        ),
    ]
