# Generated by Django 5.2.6 on 2025-12-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20251229_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingprice',
            name='cash_receipts',
            field=models.IntegerField(default=0, verbose_name='Naqd cheklar soni'),
        ),
    ]
