# Generated by Django 5.2.6 on 2026-01-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parkingprice_cash_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingprice',
            name='cash_receipts',
            field=models.IntegerField(default=0, editable=False, verbose_name='Naqd cheklar soni'),
        ),
    ]
