# Generated by Django 5.2.6 on 2025-10-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_bazaar_is_online_bazaar_server_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kamera nomi')),
                ('camera_ip', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='IP')),
                ('camera_port', models.PositiveSmallIntegerField(default=554, verbose_name='Port')),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Login')),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Parol')),
                ('bazaar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.bazaar', verbose_name='Bozor')),
            ],
        ),
    ]
