# Generated by Django 5.2.6 on 2025-10-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Kamera', 'verbose_name_plural': 'Kameralar'},
        ),
        migrations.AddField(
            model_name='camera',
            name='roi',
            field=models.JSONField(blank=True, default=None, editable=False, null=True, verbose_name='ROI'),
        ),
        migrations.AddField(
            model_name='camera',
            name='screenshot',
            field=models.ImageField(blank=True, default=None, editable=False, null=True, upload_to='', verbose_name='Screenshot'),
        ),
    ]
