# Generated by Django 5.2.6 on 2025-10-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_alter_camera_options_camera_roi_camera_screenshot'),
        ('main', '0009_alter_bazaar_server_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_mac',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Camera MAC'),
        ),
        migrations.AddField(
            model_name='camera',
            name='device_sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Device SN'),
        ),
        migrations.AddField(
            model_name='camera',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='bazaar',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, to='main.bazaar', verbose_name='Bozor'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['bazaar', 'device_sn'], name='camera_came_bazaar__9656d1_idx'),
        ),
    ]
