# Generated by Django 5.2.6 on 2025-10-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_camera_camera_mac_camera_device_sn_camera_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_ip',
            field=models.GenericIPAddressField(blank=True, default=None, editable=False, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_mac',
            field=models.CharField(blank=True, default=None, editable=False, max_length=20, null=True, verbose_name='Camera MAC'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='device_sn',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Device SN'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_online',
            field=models.BooleanField(default=False, editable=False, verbose_name='Online'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='screenshot',
            field=models.ImageField(blank=True, default=None, editable=False, null=True, upload_to='camera/screenshot', verbose_name='Screenshot'),
        ),
    ]
