# Generated by Django 5.2.6 on 2025-11-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_alter_camera_camera_ip_alter_camera_camera_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
