# Generated by Django 5.2.6 on 2025-12-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_camera_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='use_ai',
            field=models.BooleanField(default=False, verbose_name='Use AI'),
        ),
    ]
