"""
Django settings for smartbozor project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import time
from pathlib import Path
import jinja2
from django.urls import reverse_lazy
from django_jinja.builtins import DEFAULT_EXTENSIONS
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In development, fall back to a dummy key so the project can run without a .env.
SECRET_KEY = os.environ.get('SECRET_KEY') or 'dev-insecure-secret-key-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'false').lower() == 'true'

# Provide sensible defaults for local development if ALLOWED_HOSTS is not set.
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1 localhost').split()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_jinja',
    'debug_toolbar',
    'django_bootstrap5',
    'django_filters',
    'rest_framework',
    'channels',
    'django_otp',
    'django_otp.plugins.otp_totp',

    'apps.api',
    'apps.ai',
    'apps.account',
    'apps.main',
    'apps.stall',
    'apps.shop',
    'apps.parking',
    'apps.restroom',
    'apps.payment',
    'apps.report',
    'apps.rent',
    'apps.camera',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware'
]

ROOT_URLCONF = 'smartbozor.urls'

STATIC_VERSION = time.time() if DEBUG else int(os.getenv('STATIC_VERSION'))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
{
        'BACKEND': 'django_jinja.backend.Jinja2',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'OPTIONS': {
            'match_extension': 'j2',
            'undefined': jinja2.Undefined,
            'bytecode_cache': {
                'enabled': not DEBUG
            },
            'extensions': DEFAULT_EXTENSIONS + [
                "jinja2_humanize_extension.HumanizeExtension",
                "django_bootstrap5.jinja2.BootstrapTags",
                "smartbozor.jinja2_extension.SmartBozorUtils"
            ],
            'globals': {
                "DEBUG": DEBUG,
                'STATIC_VERSION': STATIC_VERSION,
            },
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',
                'smartbozor.context_processors.smartbozor',
            ],
        }
    }
]

WSGI_APPLICATION = 'smartbozor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_DEFAULT = {
    'ENGINE': 'django.db.backends.postgresql',
    'USER': os.environ["DATABASE_USER"],
    'PASSWORD': os.environ["DATABASE_PASSWORD"],
    'NAME': os.environ["DATABASE_NAME"],
    'HOST': os.environ["DATABASE_HOST"],
}

DATABASES = {
    'default': DB_DEFAULT
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES = (
    ('uz', "O'zbekcha"),
    ('ru', "Ruscha"),
    ('en', "Inglizcha"),
)

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale'
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/backend/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

STATIC_ROOT = BASE_DIR / 'static' / 'backend'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

USE_THOUSAND_SEPARATOR = True
AUTH_USER_MODEL = 'account.User'

LOGIN_URL = reverse_lazy('account:login')
LOGIN_REDIRECT_URL = reverse_lazy('dashboard:index')
LOGOUT_REDIRECT_URL = reverse_lazy('main:index')

SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE'))
SESSION_SAVE_EVERY_REQUEST = True

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

INTERNAL_IPS = [
    "127.0.0.1",
]

BOOTSTRAP5 = {
    "wrapper_class": "mb-4"
}

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_RESULT_EXPIRES = 30
CELERY_ENABLE_UTC = False

CLICKHOUSE_HOST = os.getenv('CLICKHOUSE_HOST')
CLICKHOUSE_PORT = os.getenv('CLICKHOUSE_PORT')
CLICKHOUSE_USERNAME = os.getenv('CLICKHOUSE_USERNAME')
CLICKHOUSE_PASSWORD = os.getenv('CLICKHOUSE_PASSWORD')

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.JSONParser',
        'rest_framework_xml.parsers.XMLParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework_xml.renderers.XMLRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.api.authentication.DeviceTokenAuthentication',
    ]
}

QR_CODE_LINK_HOST = "https://smart-bozor.uz"
STALL_DATASET_DIR = os.environ.get('STALL_DATASET_DIR')
STALL_TRAINING_DATASET_DIR = os.environ.get('STALL_TRAINING_DATASET_DIR')

OTP_TOTP_ISSUER = "smart-bozor.uz"
OTP_ADMIN_HIDE_SENSITIVE_DATA = os.getenv('OTP_ADMIN_HIDE_SENSITIVE_DATA', '').lower() != 'false'