# Generated by Django 5.2.6 on 2025-09-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_bazaar',
            field=models.ManyToManyField(to='main.bazaar'),
        ),
    ]
