# Generated by Django 5.2.6 on 2025-09-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_allowed_bazaar'),
        ('main', '0002_bazaar_payme_merchant_bazaar_payme_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_bazaar',
            field=models.ManyToManyField(blank=True, to='main.bazaar', verbose_name='Ruxsat berilgan bozorlar'),
        ),
    ]
