# Generated by Django 5.2.6 on 2025-09-25 19:55

from django.db import migrations

from smartbozor.partition import create_partition_table_sql


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
                          CREATE TABLE shop_shoppayment
                          (
                              id             BIGSERIAL NOT NULL,
                              shop_id        BIGINT    NOT NULL,
                              date           DATE      NOT NULL,
                              nonce          BIGINT    NOT NULL DEFAULT 0,
                              payment_method SMALLINT  NOT NULL,
                              amount         BIGINT    NOT NULL,
                              paid_at        TIMESTAMPTZ DEFAULT NULL,
                              CONSTRAINT shop_shoppayment_pkey PRIMARY KEY (id, date)
                          ) PARTITION BY RANGE ("date");
                          """,
                          reverse_sql="DROP TABLE shop_shoppayment"),
        migrations.RunSQL(
            "CREATE INDEX shop_shoppayment_shop_id_date_idx ON shop_shoppayment (shop_id, date);",
            reverse_sql="DROP INDEX shop_shoppayment_shop_id_date_idx;",
        ),
        migrations.RunSQL("""
                          CREATE TABLE shop_shopstatus
                          (
                              id          BIGSERIAL NOT NULL,
                              shop_id     BIGINT    NOT NULL,
                              date        DATE      NOT NULL,
                              is_occupied BOOLEAN   NOT NULL DEFAULT FALSE,
                              rent_price  BIGINT    NOT NULL,
                              occupied_at TIMESTAMPTZ        DEFAULT NULL,
                              CONSTRAINT shop_shopstatus_pkey PRIMARY KEY (id, date)
                          ) PARTITION BY RANGE ("date");
                          """,
                          reverse_sql="DROP TABLE shop_shopstatus"),
        migrations.RunSQL(
            "CREATE INDEX shop_shopstatus_shop_id_date_idx ON shop_shopstatus (shop_id, date);",
            reverse_sql="DROP INDEX shop_shopstatus_shop_id_date_idx;",
        ),
    ]

    for i in range(6):
        operations.append(
            migrations.RunSQL(create_partition_table_sql("shop_shoppayment", i, add_time=False),reverse_sql=migrations.RunSQL.noop),
        )
        operations.append(
            migrations.RunSQL(create_partition_table_sql("shop_shopstatus", i, add_time=False),reverse_sql=migrations.RunSQL.noop),
        )

