# Generated by Django 5.2.6 on 2025-10-01 07:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_alter_area_options'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Kun')),
                ('payment_method', models.IntegerField(default=0, verbose_name="To'lov turi")),
                ('amount', models.IntegerField(verbose_name='Narxi')),
                ('paid_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name="To'lov qilingan sana")),
            ],
            options={
                'verbose_name': "Magazin to'lovi",
                'verbose_name_plural': "Magazin to'lovlari",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Kun')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Ochilgan')),
                ('rent_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ijara narxi')),
                ('occupied_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Magazin holati',
                'verbose_name_plural': 'Magazin holatlari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+$')], verbose_name='Magazin raqami')),
                ('rent_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ijara narxi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ishlayaptimi?')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.section', verbose_name="Bo'lim nomi")),
            ],
            options={
                'verbose_name': 'Magazin',
                'verbose_name_plural': 'Magazinlar',
                'unique_together': {('section', 'number')},
            },
        ),
    ]
