# Generated by Django 5.2.6 on 2025-10-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Tadbirkor'),
        ),
    ]
