# Generated by Django 5.2.6 on 2025-10-18 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+(-[a-z0-9]+)*$')], verbose_name='Magazin raqami'),
        ),
    ]
