# Generated by Django 5.2.6 on 2025-09-25 20:55

from django.db import migrations

from smartbozor.partition import create_partition_table_sql


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
                          CREATE TABLE restroom_restroomstatus
                          (
                              id             BIGSERIAL             NOT NULL,
                              restroom_id     BIGINT                NOT NULL,
                              is_paid        BOOLEAN               NOT NULL DEFAULT FALSE,
                              payment_method INTEGER               NOT NULL DEFAULT 0,
                              price          INTEGER               NOT NULL DEFAULT 0,
                              duration       INTEGER               NOT NULL DEFAULT 0,
                              enter_at       TIMESTAMPTZ                    DEFAULT NULL,
                              leave_at       TIMESTAMPTZ                    DEFAULT NULL,
                              CONSTRAINT restroom_restroomstatus_pkey PRIMARY KEY (id, enter_at)
                          ) PARTITION BY RANGE ("enter_at");
                          """,
                          reverse_sql="DROP TABLE restroom_restroomstatus"),
        migrations.RunSQL(create_partition_table_sql("restroom_restroomstatus", 0, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("restroom_restroomstatus", 1, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("restroom_restroomstatus", 2, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("restroom_restroomstatus", 3, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("restroom_restroomstatus", 4, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("restroom_restroomstatus", 5, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            "CREATE INDEX restroom_restroomstatus_restroom_id_enter_at_idx ON restroom_restroomstatus (restroom_id, enter_at);",
            reverse_sql="DROP INDEX restroom_restroomstatus_restroom_id_enter_at_idx;",
        ),
    ]
