# Generated by Django 5.2.6 on 2025-09-25 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('restroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestroomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('payment_method', models.IntegerField(default=0, verbose_name="To'lov turi")),
                ('price', models.IntegerField(default=0, verbose_name='Narxi')),
                ('duration', models.IntegerField(default=0, verbose_name='Davomiyligi')),
                ('enter_at', models.DateTimeField(verbose_name='Kirgan vaqti')),
                ('leave_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Chiqqan vaqti')),
            ],
            options={
                'verbose_name': 'Hojatxona holati',
                'verbose_name_plural': 'Hojatxona holatlari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Hojatxona raqami')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi')),
                ('bazaar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.bazaar', verbose_name='Bozor')),
            ],
            options={
                'verbose_name': 'Hojatxona',
                'verbose_name_plural': 'Hojatxonalar',
            },
        ),
    ]
