# Generated by Django 5.2.6 on 2025-11-11 10:15

from django.db import migrations

from smartbozor.partition import create_partition_table_sql


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
                          CREATE TABLE ai_stalldataset
                          (
                              id          BIGSERIAL    NOT NULL,
                              bazaar_id   BIGSERIAL    NOT NULL,
                              camera_id   BIGSERIAL    NOT NULL,
                              image       VARCHAR(100) NOT NULL,
                              data        JSONB                 DEFAULT NULL,
                              status      SMALLINT     NOT NULL DEFAULT 0,
                              snapshot_at TIMESTAMPTZ  NOT NULL,
                              CONSTRAINT ai_stalldataset_pkey PRIMARY KEY (id, snapshot_at)
                          ) PARTITION BY RANGE ("snapshot_at");
                          """,
                          reverse_sql="DROP TABLE ai_stalldataset"),
        migrations.RunSQL(create_partition_table_sql("ai_stalldataset", 0, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("ai_stalldataset", 1, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("ai_stalldataset", 2, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("ai_stalldataset", 3, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("ai_stalldataset", 4, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("ai_stalldataset", 5, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            "CREATE INDEX ai_stalldataset_bazaar_id_status_idx ON ai_stalldataset (bazaar_id, status ASC);",
            reverse_sql="DROP INDEX ai_stalldataset_bazaar_id_status_idx;",
        ),
        migrations.RunSQL(
            "CREATE INDEX ai_stalldataset_bazaar_id_image_idx ON ai_stalldataset (bazaar_id, image);",
            reverse_sql="DROP INDEX ai_stalldataset_bazaar_id_image_idx;",
        ),
    ]
