# Generated by Django 5.2.6 on 2025-11-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StallDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Snapshot')),
                ('data', models.JSONField(verbose_name='AI data')),
                ('status', models.SmallIntegerField(db_index=True, default=0)),
                ('snapshot_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Snapshot date')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
