# Generated by Django 5.2.6 on 2025-12-14 09:18

from django.db import migrations

from smartbozor.partition import create_partition_table_sql


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                          CREATE TABLE ai_stalloccupation
                          (
                              id        BIGSERIAL   NOT NULL,
                              camera_id BIGINT      NOT NULL,
                              roi_id    UUID        NOT NULL,
                              state     SMALLINT    NOT NULL,
                              check_at  TIMESTAMPTZ NOT NULL,
                              CONSTRAINT ai_stalloccupation_pkey PRIMARY KEY (id, check_at)
                          ) PARTITION BY RANGE ("check_at");
                          """,
                          reverse_sql="DROP TABLE ai_stalloccupation"),
        migrations.RunSQL(create_partition_table_sql("ai_stalloccupation", 0, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("ai_stalloccupation", 1, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("ai_stalloccupation", 2, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("ai_stalloccupation", 3, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("ai_stalloccupation", 4, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("ai_stalloccupation", 5, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            "CREATE INDEX ai_stalloccupation_camera_id_roi_id_idx ON ai_stalloccupation (camera_id, roi_id);",
            reverse_sql="DROP INDEX ai_stalloccupation_camera_id_roi_id_idx;",
        )
    ]
