# Generated by Django 5.2.6 on 2025-12-14 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auto_20251214_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='StallOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Roi ID')),
                ('state', models.SmallIntegerField(editable=False, verbose_name='State')),
                ('check_at', models.DateTimeField(editable=False, verbose_name='Check at')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
