# Generated by Django 5.2.6 on 2025-09-25 18:22

from django.db import migrations

from smartbozor.partition import create_partition_table_sql


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
                          CREATE TABLE stall_stallstatus
                          (
                              id                BIGSERIAL       NOT NULL,
                              stall_id          BIGINT          NOT NULL,
                              date              DATE            NOT NULL,
                              is_occupied       BOOLEAN         NOT NULL DEFAULT FALSE,
                              is_paid           BOOLEAN         NOT NULL DEFAULT FALSE,
                              payment_method    INTEGER         NOT NULL DEFAULT 0,
                              price             INTEGER         NOT NULL DEFAULT 0,
                              occupied_at       TIMESTAMPTZ     DEFAULT NULL,
                              paid_at           TIMESTAMPTZ     DEFAULT NULL,
                              click_status      SMALLINT        NOT NULL DEFAULT 0,
                              payme_status      SMALLINT        NOT NULL DEFAULT 0,
                              CONSTRAINT stall_stallstatus_pkey PRIMARY KEY (id, date)
                          ) PARTITION BY RANGE ("date");
                          """,
                          reverse_sql="DROP TABLE stall_stallstatus"),
        migrations.RunSQL(create_partition_table_sql("stall_stallstatus", 0, add_time=False), reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("stall_stallstatus", 1, add_time=False), reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("stall_stallstatus", 2, add_time=False), reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("stall_stallstatus", 3, add_time=False), reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("stall_stallstatus", 4, add_time=False), reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("stall_stallstatus", 5, add_time=False), reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            "CREATE INDEX stall_stallstatus_stall_id_date_idx ON stall_stallstatus (stall_id, date);",
            reverse_sql="DROP INDEX stall_stallstatus_stall_id_date_idx;",
        ),
    ]
