# Generated by Django 5.2.6 on 2025-09-25 19:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('stall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StallStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Kun')),
                ('is_occupied', models.BooleanField(default=False, verbose_name="Band bo'lgan")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'lov qilingan")),
                ('payment_method', models.IntegerField(default=0, verbose_name="To'lov turi")),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('occupied_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Band qilingan sana')),
                ('paid_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name="To'lov qilingan sana")),
            ],
            options={
                'verbose_name': 'Rasta holati',
                'verbose_name_plural': 'Rasta holatlari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Rasta raqami')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(100)], verbose_name='Rasta narxi')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.section', verbose_name="Bo'lim nomi")),
            ],
            options={
                'verbose_name': 'Rasta',
                'verbose_name_plural': 'Rastalar',
                'unique_together': {('section', 'number')},
            },
        ),
    ]
