# Generated by Django 5.2.6 on 2025-09-27 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stall', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+$')], verbose_name='Rasta raqami'),
        ),
    ]
