# Generated by Django 5.2.6 on 2025-12-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stall', '0003_alter_stall_number'),
    ]

    operations = [
        migrations.RunSQL(
            """ALTER TABLE stall_stallstatus RENAME COLUMN click_status TO payment_progress;""",
            reverse_sql="""ALTER TABLE stall_stallstatus RENAME COLUMN payment_progress TO click_status;"""
        ),
        migrations.RunSQL(
            """ALTER TABLE stall_stallstatus DROP COLUMN payme_status;""",
            reverse_sql="""ALTER TABLE stall_stallstatus
                ADD COLUMN payme_status SMALLINT DEFAULT 0;"""
        ),
    ]
