# Generated by Django 5.2.6 on 2025-09-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bazaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Bozor nomi')),
                ('working_days', models.IntegerField(default=0, verbose_name='Ish kunlari')),
                ('payment_methods', models.IntegerField(default=0, verbose_name="To'lov turlari")),
            ],
            options={
                'verbose_name': 'Bozor',
                'verbose_name_plural': 'Bozorlar',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Tuman nomi')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Viloyat nomi')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Maydon nomi')),
                ('bazaar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.bazaar', verbose_name='Bozor')),
            ],
            options={
                'verbose_name': 'Maydon',
                'verbose_name_plural': 'Maydonlar',
            },
        ),
        migrations.AddField(
            model_name='bazaar',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.district', verbose_name='Bozor joylashgan tuman'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.region'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Bo'lim nomi")),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.area', verbose_name='Maydon')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
    ]
