# Generated by Django 5.2.6 on 2025-09-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaar',
            name='payme_merchant',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Payme merchant id'),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='payme_password',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Payme parol'),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='payme_username',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Payme login'),
        ),
    ]
