# Generated by Django 5.2.6 on 2025-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bazaar_payme_merchant_bazaar_payme_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaar',
            name='click_merchant_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='click_merchant_user_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='click_secret_key',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='click_service_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
