# Generated by Django 5.2.6 on 2025-10-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bazaar_click_merchant_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Blok', 'verbose_name_plural': 'Bloklar'},
        ),
    ]
