# Generated by Django 5.2.6 on 2025-10-04 08:42

from django.db import migrations, models

def populate_slug(apps, schema_editor):
    Bazaar = apps.get_model('main', 'Bazaar')
    for obj in Bazaar.objects.order_by('id').all():
        obj.slug = f"slug-{obj.id}"
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_area_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaar',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.RunPython(populate_slug, reverse_code=migrations.RunPython.noop),
    ]
