# Generated by Django 5.2.6 on 2025-10-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bazaar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazaar',
            name='slug',
            field=models.CharField(max_length=30, unique=True, verbose_name='Slug'),
        ),
    ]
