# Generated by Django 5.2.6 on 2025-10-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bazaar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaar',
            name='rent_pdf',
            field=models.FileField(blank=True, default=None, editable=False, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='shop_pdf',
            field=models.FileField(blank=True, default=None, editable=False, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='stall_pdf',
            field=models.FileField(blank=True, default=None, editable=False, max_length=255, null=True, upload_to=''),
        ),
    ]
