# Generated by Django 5.2.6 on 2025-10-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bazaar_rent_pdf_bazaar_shop_pdf_bazaar_stall_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaar',
            name='is_online',
            field=models.BooleanField(default=False, editable=False, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='server_ip',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='server_user',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='server_port',
            field=models.PositiveSmallIntegerField(default=22),
        ),
    ]
