# Generated by Django 5.2.6 on 2025-10-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bazaar_is_online_bazaar_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazaar',
            name='server_user',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
