# Generated by Django 5.2.6 on 2025-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bazaar_server_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaar',
            name='app_version',
            field=models.CharField(default='-', editable=False, max_length=50),
        ),
    ]
