# Generated by Django 5.2.6 on 2025-11-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bazaar_app_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bazaar',
            options={'permissions': (('bazaar_online', 'Bazaar online'),), 'verbose_name': 'Bozor', 'verbose_name_plural': 'Bozorlar'},
        ),
    ]
