# Generated by Django 5.2.6 on 2025-11-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_bazaar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaar',
            name='parking_pdf',
            field=models.FileField(blank=True, default=None, editable=False, max_length=255, null=True, upload_to=''),
        ),
    ]
