# Generated by Django 5.2.6 on 2025-12-21 13:09

from django.db import migrations

from smartbozor.partition import create_partition_table_sql


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bazaar_parking_pdf'),
    ]

    operations = [
        migrations.RunSQL("""
                          CREATE TABLE main_receipt
                          (
                              id          BIGSERIAL NOT NULL,
                              user_id     BIGINT    NOT NULL,
                              bazaar_id   BIGINT    NOT NULL,
                              object_type SMALLINT  NOT NULL,
                              object_id   BIGINT    NOT NULL,
                              amount      BIGINT    NOT NULL,
                              status      SMALLINT  NOT NULL,
                              data        JSONB        DEFAULT NULL,
                              ofd_link    VARCHAR(300) DEFAULT NULL,
                              ofd_time    BIGINT       DEFAULT 0,
                              added_at    TIMESTAMPTZ  DEFAULT NULL,
                              CONSTRAINT main_receipt_pkey PRIMARY KEY (id, added_at)
                          ) PARTITION BY RANGE ("added_at");
                          """,
                          reverse_sql="DROP TABLE main_receipt"),
        migrations.RunSQL(
            "CREATE INDEX main_receipt_bazaar_id_status_added_at_idx ON main_receipt (bazaar_id, status, added_at DESC);",
            reverse_sql="DROP INDEX main_receipt_bazaar_id_status_added_at_idx;",
        )
    ]

    for i in range(6):
        operations.append(
            migrations.RunSQL(create_partition_table_sql("main_receipt", i, add_time=False),
                              reverse_sql=migrations.RunSQL.noop),
        )

