# Generated by Django 5.2.6 on 2025-12-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20251221_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.SmallIntegerField(verbose_name='Object type')),
                ('object_id', models.BigIntegerField(verbose_name='Object ID')),
                ('amount', models.BigIntegerField(verbose_name='Narxi')),
                ('status', models.SmallIntegerField(verbose_name='Holati')),
                ('data', models.JSONField(verbose_name='Data')),
                ('ofd_link', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='OFD link')),
                ('ofd_time', models.BigIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
            ],
            options={
                'verbose_name': 'Chek',
                'verbose_name_plural': 'Cheklar',
                'managed': False,
            },
        ),
    ]
