# Generated by Django 5.2.6 on 2026-01-08 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaar',
            name='vat_percent',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='VAT percent'),
        ),
    ]
