# Generated by Django 5.2.6 on 2025-09-29 06:24

from django.db import migrations

from smartbozor.partition import create_partition_table_sql


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""
                          CREATE TABLE payment_payme
                          (
                              id                 BIGSERIAL             NOT NULL,
                              order_type         CHARACTER(1)          NOT NULL,
                              order_id           BIGINT                NOT NULL,
                              create_order_id    BIGINT                         DEFAULT 0,
                              create_order_nonce BIGINT                         DEFAULT 0,
                              payme_id           CHARACTER VARYING(50) NOT NULL,
                              amount             BIGINT                NOT NULL DEFAULT 0,
                              state              SMALLINT              NOT NULL DEFAULT 0,
                              reason             SMALLINT                       DEFAULT NULL,
                              create_time        TIMESTAMPTZ           NOT NULL,
                              perform_time       TIMESTAMPTZ                    DEFAULT NULL,
                              cancel_time        TIMESTAMPTZ                    DEFAULT NULL,
                              CONSTRAINT payment_payme_pkey PRIMARY KEY (id, create_time)
                          ) PARTITION BY RANGE ("create_time");
                          """,
                          reverse_sql="DROP TABLE payment_payme"),
        migrations.RunSQL(create_partition_table_sql("payment_payme", 0, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("payment_payme", 1, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("payment_payme", 2, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("payment_payme", 3, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("payment_payme", 4, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("payment_payme", 5, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            "CREATE INDEX payment_payme_payme_id_idx ON payment_payme (payme_id);",
            reverse_sql="DROP INDEX payment_payme_payme_id_idx;",
        ),
        migrations.RunSQL(
            'CREATE INDEX payment_payme_order_type_order_id_idx ON payment_payme (order_type, order_id);',
            reverse_sql="DROP INDEX payment_payme_order_type_order_id_idx;",
        ),
    ]
