# Generated by Django 5.2.6 on 2025-09-29 13:23

from django.db import migrations

from smartbozor.partition import create_partition_table_sql


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                          CREATE TABLE payment_click
                          (
                              id              BIGSERIAL    NOT NULL,
                              order_type      CHARACTER(1) NOT NULL,
                              order_id        BIGINT       NOT NULL,
                              create_order_id BIGINT                DEFAULT 0,
                              click_trans_id  BIGINT       NOT NULL,
                              click_paydoc_id BIGINT       NOT NULL,
                              amount          BIGINT       NOT NULL DEFAULT 0,
                              status          SMALLINT     NOT NULL DEFAULT 0,
                              prepare_time    TIMESTAMPTZ  NOT NULL,
                              complete_time   TIMESTAMPTZ           DEFAULT NULL,
                              CONSTRAINT payment_click_pkey PRIMARY KEY (id, prepare_time)
                          ) PARTITION BY RANGE ("prepare_time");
                          """,
                          reverse_sql="DROP TABLE payment_click"),
        migrations.RunSQL(create_partition_table_sql("payment_click", 0, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("payment_click", 1, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("payment_click", 2, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("payment_click", 3, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("payment_click", 4, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(create_partition_table_sql("payment_click", 5, add_time=False),
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            'CREATE INDEX payment_click_order_type_order_id_idx ON payment_click (order_type, order_id);',
            reverse_sql="DROP INDEX payment_click_order_type_order_id_idx;",
        ),
    ]
