# Generated by Django 5.2.6 on 2025-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0002_auto_20250929_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=1)),
                ('order_id', models.BigIntegerField()),
                ('create_order_id', models.BigIntegerField(default=0)),
                ('click_trans_id', models.BigIntegerField()),
                ('click_paydoc_id', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('status', models.SmallIntegerField(default=0)),
                ('prepare_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=1)),
                ('order_id', models.BigIntegerField()),
                ('payme_id', models.CharField(max_length=50)),
                ('create_order_id', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('state', models.SmallIntegerField(default=0)),
                ('reason', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('perform_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
