# Generated by Django 5.2.6 on 2025-11-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE IF EXISTS public.payment_click ADD COLUMN data jsonb DEFAULT NULL;",
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL("ALTER TABLE IF EXISTS public.payment_payme ADD COLUMN data jsonb DEFAULT NULL;",
                          reverse_sql=migrations.RunSQL.noop),
    ]
