# Generated by Django 5.2.6 on 2025-12-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bazaar_parking_pdf'),
        ('payment', '0004_auto_20251106_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('click_merchant_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('click_merchant_user_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('click_service_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('click_secret_key', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('slug', models.CharField(max_length=30, unique=True, verbose_name='Slug')),
                ('status', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.district')),
            ],
        ),
        migrations.CreateModel(
            name='PointProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fee_price', models.IntegerField(default=0)),
                ('fee_included', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payment.point')),
            ],
        ),
    ]
